version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports: 
      - "8080:80"
    networks:
      - internal
    extra_hosts:
      - host.docker.internal:host-gateway
  php:
    build: ./php
    image: php:fpm-alpine
    volumes:
      - ./app:/var/www/html/
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - internal
networks:
  internal:
    driver: bridge